export const types = {
	NEW : "CON_NEW",
	INTERRUPT : "CON_INTERRUPT",
	MSG : "CON_MSG",
	CLOSE : "CON_CLOSE",
	RESIZE : "CON_RESIZE",
	MODE_CHANGE : "MODE_CHANGE",
	STATE_CHANGE : "STATE_CHANGE",
	VAR_CHANGE : "VAR_CHANGE",
	VAR_CLEAR : "VAR_CLEAR"
}