'use strict';
export const types = {
	NEW : "PLAYER_NEW",
	LOGIN : "PLAYER_LOGIN",
	LOGOUT : "PLAYER_LOGOUT",
	SAVED : "PLAYER_SAVED",
	NOT_SAVED : "PLAYER_SAVED",
	SAVING : "PLAYER_SAVING",
	CONNECTION : "PLAYER_CONNECTION"
}