export var IAC     = 255; // interpret as command
export var DONT    = 254; // you are not to use option
export var DO      = 253; // please use option
export var WONT    = 252; // I won't use option
export var WILL    = 251; // I will use option
export var SB      = 250; // sub-negotiation
export var GA      = 249; // Go-ahead
export var EL      = 248; // Erase line
export var EC      = 247; // Erase character
export var AYT     = 246; // Are you there?
export var AO      = 245; // Abort output (but let prog finish)
export var IP      = 244; // Interrupt (permanently)
export var BREAK   = 243;
export var DM      = 242; // Data mark
export var NOP     = 241;
export var SE      = 240; // End sub-negotiation
export var EOR     = 239; // End of record (transparent mode)
export var ABORT   = 238; // Abort process
export var SUSP    = 237; // Suspend process
export var EOF     = 236; // End of file
export var SYNCH   = 242;

/* telnet options */
export var OPT_BINARY			= 0	/* 8-bit data path */
export var OPT_ECHO			= 1	/* echo */
export var OPT_RCP				= 2	/* prepare to reconnect */
export var OPT_SGA				= 3	/* suppress go ahead */
export var OPT_NAMS			= 4	/* approximate message size */
export var OPT_STATUS			= 5	/* give status */
export var OPT_TM				= 6	/* timing mark */
export var OPT_RCTE			= 7	/* remote controlled transmission and echo */
export var OPT_NAOL 			= 8	/* negotiate about output line width */
export var OPT_NAOP 			= 9	/* negotiate about output page size */
export var OPT_NAOCRD			= 10	/* negotiate about CR disposition */
export var OPT_NAOHTS			= 11	/* negotiate about horizontal tabstops */
export var OPT_NAOHTD			= 12	/* negotiate about horizontal tab disposition */
export var OPT_NAOFFD			= 13	/* negotiate about formfeed disposition */
export var OPT_NAOVTS			= 14	/* negotiate about vertical tab stops */
export var OPT_NAOVTD			= 15	/* negotiate about vertical tab disposition */
export var OPT_NAOLFD			= 16	/* negotiate about output LF disposition */
export var OPT_XASCII			= 17	/* extended ascic character set */
export var OPT_LOGOUT			= 18	/* force logout */
export var OPT_BM				= 19	/* byte macro */
export var OPT_DET				= 20	/* data entry terminal */
export var OPT_SUPDUP			= 21	/* supdup protocol */
export var OPT_SUPDUPOUTPUT 	= 22	/* supdup output */
export var OPT_SNDLOC			= 23	/* send location */
export var OPT_TTYPE			= 24	/* terminal type */
export var OPT_EOR				= 25	/* end or record */
export var OPT_TUID			= 26	/* TACACS user identification */
export var OPT_OUTMRK			= 27	/* output marking */
export var OPT_TTYLOC			= 28	/* terminal location number */
export var OPT_3270REGIME 		= 29	/* 3270 regime */
export var OPT_X3PAD			= 30	/* X.3 PAD */
export var OPT_NAWS			= 31	/* window size */
export var OPT_TSPEED			= 32	/* terminal speed */
export var OPT_LFLOW			= 33	/* remote flow control */
export var OPT_EXOPL			= 255	/* extended-options-list */

export var OPT_BINARY            = 0; // RFC 856
export var OPT_ECHO              = 1; // RFC 857
export var OPT_SUPPRESS_GO_AHEAD = 3; // RFC 858
export var OPT_STATUS            = 5; // RFC 859
export var OPT_TIMING_MARK       = 6; // RFC 860
export var OPT_TTYPE             = 24; // RFC 930, 1091
export var OPT_WINDOW_SIZE       = 31; // RFC 1073
export var OPT_LINE_MODE         = 34; // RFC 1184
export var OPT_NEW_ENVIRON       = 39; // RFC 1572
export var OPT_COMPRESS2         = 86; // http://www.zuggsoft.com/zmud/mcp.htm

export var TELQUAL_IS   = 0;
export var TELQUAL_SEND = 1;